# Praaline
# Core Library
# (c) George Christodoulides 2012-2015

! include( ../common.pri ) {
    error( Could not find the common.pri file! )
}

TEMPLATE = lib

CONFIG(debug, debug|release) {
    TARGET = pncored
} else {
    TARGET = pncore
}

CONFIG += qt thread warn_on stl rtti exceptions c++11

QT += xml sql
QT -= gui

DEFINES += PRAALINE_CORE_LIBRARY

INCLUDEPATH += . ..
DEPENDPATH += . ..

HEADERS += \
    base/BaseTypes.h \
    base/RealTime.h \
    annotation/point.h \
    annotation/interval.h \
    annotation/annotationtier.h \
    annotation/intervaltier.h \
    annotation/pointtier.h \
    annotation/annotationtiergroup.h \
    corpus/corpusobject.h \
    corpus/corpuscommunication.h \
    corpus/corpusannotation.h \
    corpus/corpusrecording.h \
    corpus/corpus.h \
    corpus/corpusspeaker.h \
    corpus/corpusparticipation.h \
    corpus/corpusbookmark.h \
    structure/annotationstructure.h \
    structure/annotationstructureattribute.h \
    structure/annotationstructurelevel.h \
    structure/metadatastructureattribute.h \
    structure/metadatastructure.h \
    structure/metadatastructuresection.h \
    interfaces/praat/praattextfile.h \
    interfaces/praat/praattextgrid.h \
    interfaces/exmaralda/exmaraldabasictranscription.h \
    interfaces/exmaralda/exmaraldatranscriptionbridge.h \
    serialisers/xml/xmlserialiserannotationstructure.h \
    serialisers/xml/xmlserialisermetadatastructure.h \
    serialisers/xml/xmlserialiserbase.h \
    serialisers/xml/xmlserialisercorpus.h \
    serialisers/sql/sqlserialiserbase.h \
    serialisers/sql/sqlserialisercorpus.h \
    serialisers/sql/sqlserialisermetadatastructure.h \
    serialisers/sql/sqlserialiserannotationstructure.h \
    serialisers/sql/sqlschemaproxymetadata.h \
    serialisers/sql/sqlschemaproxyannotation.h \
    serialisers/sql/sqlserialiserannotation.h \
    query/querydefinition.h \
    serialisers/datastoreinfo.h \
    serialisers/abstractmetadatadatastore.h \
    serialisers/abstractannotationdatastore.h \
    serialisers/sql/sqlannotationdatastore.h \
    serialisers/datastorefactory.h \
    serialisers/sql/sqlmetadatadatastore.h \
    serialisers/sql/sqlschemaproxybase.h \
    serialisers/xml/xmlannotationdatastore.h \
    serialisers/xml/xmlmetadatadatastore.h \
    serialisers/xml/xmlserialiserannotation.h \
    serialisers/corpusdefinition.h \
    pncore_global.h \
    annotation/annotationdatatable.h \
    annotation/speakertimeline.h \
    serialisers/xml/xmlserialisercorpusbookmark.h \
    structure/structurebase.h \
    query/queryoccurrence.h \
    serialisers/sql/sqlqueryengineannotation.h \
    query/queryfiltergroup.h \
    query/queryfiltersequence.h \
    interfaces/subtitles/subtitlesfile.h \
    interfaces/interfacetextfile.h \
    annotation/annotationelement.h \
    annotation/relationtier.h \
    annotation/treetier.h \
    interfaces/transcriber/transcriberannotationgraph.h \
    interfaces/praat/PraatPointTierFile.h \
    interfaces/anvil/AnvilMetadataTranscript.h \
    base/RealValueList.h \
    statistics/StatisticalSummary.h \
    statistics/StatisticalMeasureDefinition.h \
    statistics/HistogramCalculator.h \
    QSqlMigrator/Structure/Column.h \
    QSqlMigrator/Structure/Index.h \
    QSqlMigrator/Structure/LocalScheme.h \
    QSqlMigrator/Structure/Table.h \
    QSqlMigrator/Scheme/Database.h \
    QSqlMigrator/Scheme/DbColumn.h \
    QSqlMigrator/Scheme/DbTable.h \
    QSqlMigrator/Helper/ColumnService.h \
    QSqlMigrator/Helper/HelperRepository.h \
    QSqlMigrator/Helper/QuoteService.h \
    QSqlMigrator/Helper/SqlStructureService.h \
    QSqlMigrator/Helper/TypeMapperService.h \
    QSqlMigrator/Commands/AddColumn.h \
    QSqlMigrator/Commands/AlterColumnType.h \
    QSqlMigrator/Commands/BaseCommand.h \
    QSqlMigrator/Commands/CreateIndex.h \
    QSqlMigrator/Commands/CreateTable.h \
    QSqlMigrator/Commands/CustomCommandBase.h \
    QSqlMigrator/Commands/DropColumn.h \
    QSqlMigrator/Commands/DropIndex.h \
    QSqlMigrator/Commands/DropTable.h \
    QSqlMigrator/Commands/RenameColumn.h \
    QSqlMigrator/Commands/RenameTable.h \
    QSqlMigrator/Migrations/Migration.h \
    QSqlMigrator/Migrations/MigrationRepository.h \
    QSqlMigrator/Migrations/RegisterMigration.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlAddColumnService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlAlterColumnTypeService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlCreateIndexService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlCreateTableService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropColumnService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropIndexService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropTableService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlRenameColumnService.h \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlRenameTableService.h \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlColumnService.h \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlQuoteService.h \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlTypeMapperService.h \
    QSqlMigrator/BaseSqlMigrator/MigrationTracker/BaseMigrationTableService.h \
    QSqlMigrator/CommandExecution/BaseCommandExecutionService.h \
    QSqlMigrator/CommandExecution/CommandExecutionContext.h \
    QSqlMigrator/CommandExecution/CommandExecutionService.h \
    QSqlMigrator/CommandExecution/CommandExecutionServiceRepository.h \
    QSqlMigrator/CommandExecution/CustomCommandService.h \
    QSqlMigrator/CommandExecution/LocalSchemeBaseCommandExecutionService.h \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionContext.h \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionService.h \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionServiceRepository.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeAddColumnService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeAlterColumnTypeService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeCreateIndexService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeCreateTableService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropColumnService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropIndexService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropTableService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeRenameColumnService.h \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeRenameTableService.h \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeComparisonContext.h \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeComparisonService.h \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeMigrator.h \
    QSqlMigrator/MigrationExecution/LocalSchemeMigrationExecutionContext.h \
    QSqlMigrator/MigrationExecution/LocalSchemeMigrationExecutionService.h \
    QSqlMigrator/MigrationExecution/MigrationExecutionConfig.h \
    QSqlMigrator/MigrationExecution/MigrationExecutionContext.h \
    QSqlMigrator/MigrationExecution/MigrationExecutionService.h \
    QSqlMigrator/MigrationTracker/MigrationTrackerService.h \
    QSqlMigrator/QSqlMigrator/QSqlMigratorConfig.h \
    QSqlMigrator/QSqlMigrator/QSqlMigratorService.h \
    QSqlMigrator/QSqlMigrator.h \
    QSqlMigrator/QSqlMigratorConfig.h \
    QSqlMigrator/Databases/SqliteMigrator/SqliteMigrator.h \
    QSqlMigrator/Databases/SqliteMigrator/DatabaseLock.h \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteAlterColumnService.h \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteAlterColumnTypeService.h \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteDropColumnService.h \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteRenameColumnService.h \
    QSqlMigrator/Databases/SqliteMigrator/Helper/SqliteSqlStructureService.h \
    QSqlMigrator/Databases/SqliteMigrator/MigrationTracker/SqliteMigrationTableService.h \
    QSqlMigrator/Databases/MysqlMigrator/MysqlMigrator.h \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlColumnService.h \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlStructureService.h \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlTypeMapperService.h \
    QSqlMigrator/Databases/MysqlMigrator/CommandExecution/MysqlAlterColumnTypeService.h \
    QSqlMigrator/Databases/MysqlMigrator/CommandExecution/MysqlRenameColumnService.h \
    QSqlMigrator/Databases/FirebirdMigrator/FirebirdMigrator.h \
    QSqlMigrator/Databases/FirebirdMigrator/Helper/FirebirdSqlStructureService.h \
    QSqlMigrator/Databases/PostgresqlMigrator/PostgresqlMigrator.h \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlColumnService.h \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlQuoteService.h \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlStructureService.h \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlTypeMapperService.h \
    base/DataType.h \
    QSqlMigrator/Structure/SqlType.h

SOURCES += \
    base/RealTime.cpp \
    annotation/point.cpp \
    annotation/interval.cpp \
    annotation/annotationtier.cpp \
    annotation/intervaltier.cpp \
    annotation/pointtier.cpp \
    annotation/annotationtiergroup.cpp \
    corpus/corpuscommunication.cpp \
    corpus/corpusannotation.cpp \
    corpus/corpusrecording.cpp \
    corpus/corpus.cpp \
    corpus/corpusspeaker.cpp \
    corpus/corpusobject.cpp \
    corpus/corpusparticipation.cpp \
    corpus/corpusbookmark.cpp \
    structure/annotationstructure.cpp \
    structure/annotationstructureattribute.cpp \
    structure/annotationstructurelevel.cpp \
    structure/metadatastructureattribute.cpp \
    structure/metadatastructure.cpp \
    structure/metadatastructuresection.cpp \
    interfaces/praat/praattextfile.cpp \
    interfaces/praat/praattextgrid.cpp \
    interfaces/exmaralda/exmaraldabasictranscription.cpp \
    interfaces/exmaralda/exmaraldatranscriptionbridge.cpp \
    serialisers/xml/xmlserialiserannotationstructure.cpp \
    serialisers/xml/xmlserialisermetadatastructure.cpp \
    serialisers/xml/xmlserialiserbase.cpp \
    serialisers/xml/xmlserialisercorpus.cpp \
    serialisers/sql/sqlserialiserbase.cpp \
    serialisers/sql/sqlserialisercorpus.cpp \
    serialisers/sql/sqlserialisermetadatastructure.cpp \
    serialisers/sql/sqlserialiserannotationstructure.cpp \
    serialisers/sql/sqlschemaproxyannotation.cpp \
    serialisers/sql/sqlserialiserannotation.cpp \
    query/querydefinition.cpp \
    serialisers/sql/sqlannotationdatastore.cpp \
    serialisers/datastorefactory.cpp \
    serialisers/sql/sqlmetadatadatastore.cpp \
    serialisers/sql/sqlschemaproxybase.cpp \
    serialisers/xml/xmlannotationdatastore.cpp \
    serialisers/xml/xmlmetadatadatastore.cpp \
    serialisers/xml/xmlserialiserannotation.cpp \
    serialisers/corpusdefinition.cpp \
    annotation/annotationdatatable.cpp \
    annotation/speakertimeline.cpp \
    serialisers/xml/xmlserialisercorpusbookmark.cpp \
    structure/structurebase.cpp \
    query/queryoccurrence.cpp \
    serialisers/sql/sqlqueryengineannotation.cpp \
    query/queryfiltergroup.cpp \
    query/queryfiltersequence.cpp \
    interfaces/subtitles/subtitlesfile.cpp \
    interfaces/interfacetextfile.cpp \
    annotation/annotationelement.cpp \
    annotation/relationtier.cpp \
    annotation/treetier.cpp \
    interfaces/transcriber/transcriberannotationgraph.cpp \
    interfaces/praat/PraatPointTierFile.cpp \
    interfaces/anvil/AnvilMetadataTranscript.cpp \
    base/RealValueList.cpp \
    statistics/StatisticalSummary.cpp \
    statistics/StatisticalMeasureDefinition.cpp \
    statistics/HistogramCalculator.cpp \
    QSqlMigrator/Structure/Column.cpp \
    QSqlMigrator/Structure/Index.cpp \
    QSqlMigrator/Structure/LocalScheme.cpp \
    QSqlMigrator/Structure/Table.cpp \
    QSqlMigrator/Scheme/Database.cpp \
    QSqlMigrator/Scheme/DbColumn.cpp \
    QSqlMigrator/Scheme/DbTable.cpp \
    QSqlMigrator/Helper/HelperRepository.cpp \
    QSqlMigrator/Commands/AddColumn.cpp \
    QSqlMigrator/Commands/AlterColumnType.cpp \
    QSqlMigrator/Commands/BaseCommand.cpp \
    QSqlMigrator/Commands/CreateIndex.cpp \
    QSqlMigrator/Commands/CreateTable.cpp \
    QSqlMigrator/Commands/CustomCommandBase.cpp \
    QSqlMigrator/Commands/DropColumn.cpp \
    QSqlMigrator/Commands/DropIndex.cpp \
    QSqlMigrator/Commands/DropTable.cpp \
    QSqlMigrator/Commands/RenameColumn.cpp \
    QSqlMigrator/Commands/RenameTable.cpp \
    QSqlMigrator/Migrations/Migration.cpp \
    QSqlMigrator/Migrations/MigrationRepository.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlAddColumnService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlAlterColumnTypeService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlCreateIndexService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlCreateTableService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropColumnService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropIndexService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlDropTableService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlRenameColumnService.cpp \
    QSqlMigrator/BaseSqlMigrator/CommandExecution/BaseSqlRenameTableService.cpp \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlColumnService.cpp \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlQuoteService.cpp \
    QSqlMigrator/BaseSqlMigrator/Helper/BaseSqlTypeMapperService.cpp \
    QSqlMigrator/BaseSqlMigrator/MigrationTracker/BaseMigrationTableService.cpp \
    QSqlMigrator/CommandExecution/BaseCommandExecutionService.cpp \
    QSqlMigrator/CommandExecution/CommandExecutionContext.cpp \
    QSqlMigrator/CommandExecution/CommandExecutionService.cpp \
    QSqlMigrator/CommandExecution/CommandExecutionServiceRepository.cpp \
    QSqlMigrator/CommandExecution/CustomCommandService.cpp \
    QSqlMigrator/CommandExecution/LocalSchemeBaseCommandExecutionService.cpp \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionContext.cpp \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionService.cpp \
    QSqlMigrator/CommandExecution/LocalSchemeCommandExecutionServiceRepository.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeAddColumnService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeAlterColumnTypeService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeCreateIndexService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeCreateTableService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropColumnService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropIndexService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeDropTableService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeRenameColumnService.cpp \
    QSqlMigrator/LocalSchemeMigrator/CommandExecution/LocalSchemeRenameTableService.cpp \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeComparisonContext.cpp \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeComparisonService.cpp \
    QSqlMigrator/LocalSchemeMigrator/LocalSchemeMigrator.cpp \
    QSqlMigrator/MigrationExecution/LocalSchemeMigrationExecutionContext.cpp \
    QSqlMigrator/MigrationExecution/LocalSchemeMigrationExecutionService.cpp \
    QSqlMigrator/MigrationExecution/MigrationExecutionConfig.cpp \
    QSqlMigrator/MigrationExecution/MigrationExecutionContext.cpp \
    QSqlMigrator/MigrationExecution/MigrationExecutionService.cpp \
    QSqlMigrator/QSqlMigrator/QSqlMigratorConfig.cpp \
    QSqlMigrator/QSqlMigrator/QSqlMigratorService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/SqliteMigrator.cpp \
    QSqlMigrator/Databases/SqliteMigrator/DatabaseLock.cpp \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteAlterColumnService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteAlterColumnTypeService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteDropColumnService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/CommandExecution/SqliteRenameColumnService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/Helper/SqliteSqlStructureService.cpp \
    QSqlMigrator/Databases/SqliteMigrator/MigrationTracker/SqliteMigrationTableService.cpp \
    QSqlMigrator/Databases/MysqlMigrator/MysqlMigrator.cpp \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlColumnService.cpp \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlStructureService.cpp \
    QSqlMigrator/Databases/MysqlMigrator/Helper/MysqlTypeMapperService.cpp \
    QSqlMigrator/Databases/MysqlMigrator/CommandExecution/MysqlAlterColumnTypeService.cpp \
    QSqlMigrator/Databases/MysqlMigrator/CommandExecution/MysqlRenameColumnService.cpp \
    QSqlMigrator/Databases/FirebirdMigrator/FirebirdMigrator.cpp \
    QSqlMigrator/Databases/FirebirdMigrator/Helper/FirebirdSqlStructureService.cpp \
    QSqlMigrator/Databases/PostgresqlMigrator/PostgresqlMigrator.cpp \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlColumnService.cpp \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlQuoteService.cpp \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlStructureService.cpp \
    QSqlMigrator/Databases/PostgresqlMigrator/Helper/PostgresqlTypeMapperService.cpp \
    serialisers/sql/sqlschemaproxymetadata.cpp \
    base/DataType.cpp \
    QSqlMigrator/Structure/SqlType.cpp

DISTFILES += \
    pncore.qmodel
