/*
 * Internal module API header file.
 *
 * Generated by SIP 4.16.5 on Wed Dec 02 22:06:18 2015
 */

#ifndef _PraalinePyAPI_H
#define _PraalinePyAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_fromMilliseconds 0
#define sipName_fromMilliseconds &sipStrings_PraalinePy[0]
#define sipNameNr_fromXsdDuration 17
#define sipName_fromXsdDuration &sipStrings_PraalinePy[17]
#define sipNameNr_fromNanoseconds 33
#define sipName_fromNanoseconds &sipStrings_PraalinePy[33]
#define sipNameNr_frame2RealTime 49
#define sipName_frame2RealTime &sipStrings_PraalinePy[49]
#define sipNameNr_realTime2Frame 64
#define sipName_realTime2Frame &sipStrings_PraalinePy[64]
#define sipNameNr_toXsdDuration 79
#define sipName_toXsdDuration &sipStrings_PraalinePy[79]
#define sipNameNr_toNanoseconds 93
#define sipName_toNanoseconds &sipStrings_PraalinePy[93]
#define sipNameNr_toFrameText 107
#define sipName_toFrameText &sipStrings_PraalinePy[107]
#define sipNameNr_fromSeconds 119
#define sipName_fromSeconds &sipStrings_PraalinePy[119]
#define sipNameNr_std__string 131
#define sipName_std__string &sipStrings_PraalinePy[131]
#define sipNameNr_fromString 143
#define sipName_fromString &sipStrings_PraalinePy[143]
#define sipNameNr_PraalinePy 154
#define sipName_PraalinePy &sipStrings_PraalinePy[154]
#define sipNameNr_toSecText 165
#define sipName_toSecText &sipStrings_PraalinePy[165]
#define sipNameNr_zeroTime 175
#define sipName_zeroTime &sipStrings_PraalinePy[175]
#define sipNameNr_toString 184
#define sipName_toString &sipStrings_PraalinePy[184]
#define sipNameNr_toDouble 193
#define sipName_toDouble &sipStrings_PraalinePy[193]
#define sipNameNr_RealTime 55
#define sipName_RealTime &sipStrings_PraalinePy[55]
#define sipNameNr_toText 202
#define sipName_toText &sipStrings_PraalinePy[202]
#define sipNameNr_string 136
#define sipName_string &sipStrings_PraalinePy[136]
#define sipNameNr_msec 209
#define sipName_msec &sipStrings_PraalinePy[209]
#define sipNameNr_usec 214
#define sipName_usec &sipStrings_PraalinePy[214]
#define sipNameNr_nsec 219
#define sipName_nsec &sipStrings_PraalinePy[219]
#define sipNameNr_abs 224
#define sipName_abs &sipStrings_PraalinePy[224]
#define sipNameNr_sec 210
#define sipName_sec &sipStrings_PraalinePy[210]

#define sipMalloc                   sipAPI_PraalinePy->api_malloc
#define sipFree                     sipAPI_PraalinePy->api_free
#define sipBuildResult              sipAPI_PraalinePy->api_build_result
#define sipCallMethod               sipAPI_PraalinePy->api_call_method
#define sipCallErrorHandler         sipAPI_PraalinePy->api_call_error_handler
#define sipParseResultEx            sipAPI_PraalinePy->api_parse_result_ex
#define sipParseResult              sipAPI_PraalinePy->api_parse_result
#define sipParseArgs                sipAPI_PraalinePy->api_parse_args
#define sipParseKwdArgs             sipAPI_PraalinePy->api_parse_kwd_args
#define sipParsePair                sipAPI_PraalinePy->api_parse_pair
#define sipCommonDtor               sipAPI_PraalinePy->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_PraalinePy->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_PraalinePy->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_PraalinePy->api_convert_to_void_ptr
#define sipAddException             sipAPI_PraalinePy->api_add_exception
#define sipNoFunction               sipAPI_PraalinePy->api_no_function
#define sipNoMethod                 sipAPI_PraalinePy->api_no_method
#define sipAbstractMethod           sipAPI_PraalinePy->api_abstract_method
#define sipBadClass                 sipAPI_PraalinePy->api_bad_class
#define sipBadCatcherResult         sipAPI_PraalinePy->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_PraalinePy->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_PraalinePy->api_bad_operator_arg
#define sipTrace                    sipAPI_PraalinePy->api_trace
#define sipTransferBack             sipAPI_PraalinePy->api_transfer_back
#define sipTransferTo               sipAPI_PraalinePy->api_transfer_to
#define sipTransferBreak            sipAPI_PraalinePy->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_PraalinePy->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_PraalinePy->api_wrapper_type
#define sipWrapperType_Type         sipAPI_PraalinePy->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_PraalinePy->api_voidptr_type
#define sipGetPyObject              sipAPI_PraalinePy->api_get_pyobject
#define sipGetAddress               sipAPI_PraalinePy->api_get_address
#define sipGetMixinAddress          sipAPI_PraalinePy->api_get_mixin_address
#define sipGetCppPtr                sipAPI_PraalinePy->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_PraalinePy->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_PraalinePy->api_is_py_method
#define sipCallHook                 sipAPI_PraalinePy->api_call_hook
#define sipEndThread                sipAPI_PraalinePy->api_end_thread
#define sipConnectRx                sipAPI_PraalinePy->api_connect_rx
#define sipDisconnectRx             sipAPI_PraalinePy->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_PraalinePy->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_PraalinePy->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_PraalinePy->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_PraalinePy->api_add_type_instance
#define sipFreeSipslot              sipAPI_PraalinePy->api_free_sipslot
#define sipSameSlot                 sipAPI_PraalinePy->api_same_slot
#define sipPySlotExtend             sipAPI_PraalinePy->api_pyslot_extend
#define sipConvertRx                sipAPI_PraalinePy->api_convert_rx
#define sipAddDelayedDtor           sipAPI_PraalinePy->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_PraalinePy->api_can_convert_to_type
#define sipConvertToType            sipAPI_PraalinePy->api_convert_to_type
#define sipForceConvertToType       sipAPI_PraalinePy->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_PraalinePy->api_can_convert_to_enum
#define sipReleaseType              sipAPI_PraalinePy->api_release_type
#define sipConvertFromType          sipAPI_PraalinePy->api_convert_from_type
#define sipConvertFromNewType       sipAPI_PraalinePy->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_PraalinePy->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_PraalinePy->api_convert_from_enum
#define sipGetState                 sipAPI_PraalinePy->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_PraalinePy->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_PraalinePy->api_export_symbol
#define sipImportSymbol             sipAPI_PraalinePy->api_import_symbol
#define sipFindType                 sipAPI_PraalinePy->api_find_type
#define sipFindNamedEnum            sipAPI_PraalinePy->api_find_named_enum
#define sipBytes_AsChar             sipAPI_PraalinePy->api_bytes_as_char
#define sipBytes_AsString           sipAPI_PraalinePy->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_PraalinePy->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_PraalinePy->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_PraalinePy->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_PraalinePy->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_PraalinePy->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_PraalinePy->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_PraalinePy->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_PraalinePy->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_PraalinePy->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_PraalinePy->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_PraalinePy->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_PraalinePy->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_PraalinePy->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_PraalinePy->api_save_slot
#define sipClearAnySlotReference    sipAPI_PraalinePy->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_PraalinePy->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_PraalinePy->api_deprecated
#define sipKeepReference            sipAPI_PraalinePy->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_PraalinePy->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_PraalinePy->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_PraalinePy->api_type_from_py_type_object
#define sipTypeScope                sipAPI_PraalinePy->api_type_scope
#define sipResolveTypedef           sipAPI_PraalinePy->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_PraalinePy->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_PraalinePy->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_PraalinePy->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_PraalinePy->api_enable_autoconversion
#define sipInitMixin                sipAPI_PraalinePy->api_init_mixin
#define sipExportModule             sipAPI_PraalinePy->api_export_module
#define sipInitModule               sipAPI_PraalinePy->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_PraalinePy->api_map_string_to_class
#define sipMapIntToClass            sipAPI_PraalinePy->api_map_int_to_class
#define sipFindClass                sipAPI_PraalinePy->api_find_class
#define sipFindMappedType           sipAPI_PraalinePy->api_find_mapped_type
#define sipConvertToArray           sipAPI_PraalinePy->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_PraalinePy->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_PraalinePy->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_PraalinePy[];

#define sipType_RealTime              sipModuleAPI_PraalinePy.em_types[0]
#define sipClass_RealTime             sipModuleAPI_PraalinePy.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PraalinePy_RealTime;

#define sipType_std_string      sipModuleAPI_PraalinePy.em_types[1]

extern sipMappedTypeDef sipTypeDef_PraalinePy_std_string;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_PraalinePy;
extern sipExportedModuleDef sipModuleAPI_PraalinePy;

#endif
