#ifndef PLUGINDISMO2_GLOBAL_H
#define PLUGINDISMO2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_DISMO2_LIBRARY)
#  define PLUGIN_DISMO2_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_DISMO2_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINDISMO2_GLOBAL_H
