#ifndef PLUGIN_WEBSIMPLECMS_GLOBAL_H
#define PLUGIN_WEBSIMPLECMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_WEBSIMPLECMS_LIBRARY)
#  define PLUGIN_WEBSIMPLECMS_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_WEBSIMPLECMS_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_WEBSIMPLECMS_GLOBAL_H
