/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.5 on Wed Dec 09 23:41:25 2015
 */

#include "sipAPIPraalinePy.h"

#line 20 "D:/DEVELOP/Praaline/praalinepy/std_string.sip"
#include <string>
#line 12 "D:/DEVELOP/Praaline/praalinepy/sipOutput/sipPraalinePystdstring.cpp"



extern "C" {static void assign_std_string(void *, SIP_SSIZE_T, const void *);}
static void assign_std_string(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<std::string *>(sipDst)[sipDstIdx] = *reinterpret_cast<const std::string *>(sipSrc);
}


extern "C" {static void *array_std_string(SIP_SSIZE_T);}
static void *array_std_string(SIP_SSIZE_T sipNrElem)
{
    return new std::string[sipNrElem];
}


extern "C" {static void *copy_std_string(const void *, SIP_SSIZE_T);}
static void *copy_std_string(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new std::string(reinterpret_cast<const std::string *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_std_string(void *, int);}
static void release_std_string(void *ptr, int)
{
    delete reinterpret_cast<std::string *>(ptr);
}



extern "C" {static int convertTo_std_string(PyObject *, void **, int *, PyObject *);}
static int convertTo_std_string(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *)
{
    std::string **sipCppPtr = reinterpret_cast<std::string **>(sipCppPtrV);

#line 35 "D:/DEVELOP/Praaline/praalinepy/std_string.sip"
	// Allow a Python string (or a unicode string) whenever a string is expected.
	// If argument is a Unicode string, just decode it to UTF-8
	// If argument is a Python string, assume it's UTF-8
	if (sipIsErr == NULL)
		return (PyBytes_Check(sipPy) || PyUnicode_Check(sipPy));
	if (sipPy == Py_None) {
		*sipCppPtr = new std::string;
		return 1;
	}
	if (PyUnicode_Check(sipPy)) {
		PyObject* s = PyUnicode_AsEncodedString(sipPy, "UTF-8", "");
		*sipCppPtr = new std::string(PyBytes_AS_STRING(s));
		Py_DECREF(s);
		return 1;
	}
	if (PyBytes_Check(sipPy)) {
		*sipCppPtr = new std::string(PyBytes_AS_STRING(sipPy));
		return 1;
	}
	return 0;
#line 72 "D:/DEVELOP/Praaline/praalinepy/sipOutput/sipPraalinePystdstring.cpp"
}


extern "C" {static PyObject *convertFrom_std_string(void *, PyObject *);}
static PyObject *convertFrom_std_string(void *sipCppV, PyObject *)
{
   std::string *sipCpp = reinterpret_cast<std::string *>(sipCppV);

#line 24 "D:/DEVELOP/Praaline/praalinepy/std_string.sip"
	// convert an std::string to a Python (unicode) string
	PyObject* newstring;
	newstring = PyUnicode_DecodeUTF8(sipCpp->c_str(), sipCpp->length(), NULL);
	if(newstring == NULL) {
		PyErr_Clear();
		newstring = PyBytes_FromString(sipCpp->c_str());
	}
	return newstring;
#line 90 "D:/DEVELOP/Praaline/praalinepy/sipOutput/sipPraalinePystdstring.cpp"
}


sipMappedTypeDef sipTypeDef_PraalinePy_std_string = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_std__string,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_std_string,
    array_std_string,
    copy_std_string,
    release_std_string,
    convertTo_std_string,
    convertFrom_std_string
};
