#ifndef PLUGINMETRONOME_GLOBAL_H
#define PLUGINMETRONOME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_METRONOME_LIBRARY)
#  define PLUGIN_METRONOME_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_METRONOME_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINMETRONOME_GLOBAL_H
