#!/bin/bash
mypath=`pwd`/`dirname $0`
deproot="$mypath"/../../
prefix="$deproot"/win64-mingw
CXX="x86_64-w64-mingw32-g++ -I$prefix/include -L$prefix/lib" CC="x86_64-w64-mingw32-gcc -I$prefix/include -L$prefix/lib" ./configure --prefix=$prefix/ --host=x86_64-unknown-windows "$@"

