#ifndef PLUGINDISFLUENCYANALYSER_GLOBAL_H
#define PLUGINDISFLUENCYANALYSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_DISFLUENCYANALYSER_LIBRARY)
#  define PLUGIN_DISFLUENCYANALYSER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_DISFLUENCYANALYSER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINDISFLUENCYANALYSER_GLOBAL_H
