#ifndef PLUGINPROMISE_GLOBAL_H
#define PLUGINPROMISE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_PROMISE_LIBRARY)
#  define PLUGIN_PROMISE_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_PROMISE_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROMISE_GLOBAL_H
