#ifndef PLUGINPROSOBOX_GLOBAL_H
#define PLUGINPROSOBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_PROSOBOX_LIBRARY)
#  define PLUGIN_PROSOBOX_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_PROSOBOX_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROSOBOX_GLOBAL_H
