#ifndef PLUGINMBROLA_GLOBAL_H
#define PLUGINMBROLA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_MBROLA_LIBRARY)
#  define PLUGIN_MBROLA_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_MBROLA_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINMBROLA_GLOBAL_H
