#ifndef PLUGIN_ALIGNER_GLOBAL_H
#define PLUGIN_ALIGNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_ALIGNER_LIBRARY)
#  define PLUGIN_ALIGNER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_ALIGNER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_ALIGNER_GLOBAL_H
