#ifndef PLUGIN_ANONYMISER_GLOBAL_H
#define PLUGIN_ANONYMISER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_ANONYMISER_LIBRARY)
#  define PLUGIN_ANONYMISER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_ANONYMISER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_ANONYMISER_GLOBAL_H
